//file to handle the main modules for app

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
//imported for 2 way binding then added to imports array below
import {FormsModule} from '@angular/forms';
//for communicating with servers over http
import {HttpClientModule} from '@angular/common/http';
//simulate REST server
import { HttpClientInMemoryWebApiModule } from 'angular-in-memory-web-api';
//use to prime test db server
import { InMemoryDataService }  from './in-memory-data.service';

import { AppComponent } from './app.component';
//auto generated by ng generate component heroes
import { HeroesComponent } from './heroes/heroes.component';
import { HeroDetailComponent } from './hero-detail/hero-detail.component';
import { MessagesComponent } from './messages/messages.component';
import { AppRoutingModule } from './app-routing.module';
import { DashboardComponent } from './dashboard/dashboard.component';
//metadata for app
//need to place imports in array and components in declarations
@NgModule({
  declarations: [
    AppComponent,
    HeroesComponent,
    HeroDetailComponent,
    MessagesComponent,
    DashboardComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    AppRoutingModule,
    HttpClientModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
